### ISSUE TITLE
Commit without `git add .`

### ISSUE THREAD

**Issue by saneef** [ZeroX-DG/CommitTasks#3]
The `ct -c` command runs `git add` ([code](https://github.com/ZeroX-DG/CommitTasks/blob/master/src/git-api.js#L4)). On big projects as well as while developing big features it might problematic. Would it make sense to let the `ct -c` only do the commit, not the adding. May be the 'adding' can be optional using come flags.

What do you think @ZeroX-DG ?

**Comment by MrWeb** [comment]
Totally agree @saneef

**Comment by ZeroX-DG** [comment]
Yes I agree and was planing on removing `git add .` in the next release, thank you @MrWeb for the PR.

**Comment by ZeroX-DG** [comment]
In the next release, the custom files flag will be available and the user can use that flag to specify the files that they want to commit.
